### ISSUE TITLE
Auth error when trying to use Basic Native auth

### ISSUE THREAD

**Issue by jasonf20** [docker/docker-registry#1027]
Hello, Im using docker version 1.7.1 and docker registry image 2.1. 

I have set up Basic Native auth as the docs state but keep getting this at login: `Error response from daemon: no successful auth challenge for https://localhost:5000/v2/ - errors: []` 

I have set up TLS and it works fine without the auth. But the auth does not seem to work

**Comment by dmp42** [comment]
Did you `docker login myregistrydomain`?

Can you provide your registry+docker daemon logs and configuration?

Did you try following the documentation step by step?

Thanks.

**Comment by jasonf20** [comment]
@dmp42 Yea of course, I get that message when trying to log in. Here is my compose:

```
registry:
  environment:
    REGISTRY_STORAGE: "s3"
    REGISTRY_STORAGE_S3_ACCESSKEY: "XXXX"
    REGISTRY_STORAGE_S3_SECRETKEY: "XXXX"
    REGISTRY_STORAGE_S3_BUCKET: "my-docker-registry"
    REGISTRY_STORAGE_PATH: "/registry"
    REGISTRY_STORAGE_S3_REGION: "eu-west-1"
    REGISTRY_SEARCH_BACKEND: "sqlalchemy"
    REGISTRY_LOG_LEVEL: "debug"
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/docker.crt
    REGISTRY_HTTP_TLS_KEY: /certs/docker.key
    REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
  volumes:
    - ssl:/certs
    - auth:/auth
  image: registry:2
  ports:
    - "5000:5000"
```

And here are the logs:

```
0-90c1-507f6b77a17d service=registry version=v2.1.0 
registry_1 | time="2015-08-12T14:35:01.665453805Z" level=info msg="Starting upload purge in 45m0s" instance.id=2db8d040-8f05-4b70-90c1-507f6b77a17d service=registry version=v2.1.0 
registry_1 | time="2015-08-12T14:35:01.780740531Z" level=info msg="listening on [::]:5000, tls" instance.id=2db8d040-8f05-4b70-90c1-507f6b77a17d service=registry version=v2.1.0 
registry_1 | time="2015-08-12T14:35:12.043408294Z" level=debug msg="s3.List(\"/\")" instance.id=2db8d040-8f05-4b70-90c1-507f6b77a17d service=registry trace.duration=358.497214ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=4f85aa6b-c9c8-4a3f-9f9d-597de744d037 trace.line=123 version=v2.1.0 
registry_1 | time="2015-08-12T14:35:13.875133769Z" level=debug msg="authorizing request" http.request.host="localhost:5000" http.request.id=20854bc8-3998-453c-a0a1-19cf40eab5bb http.request.method=GET http.request.remoteaddr="172.17.42.1:36770" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-38-generic os/linux arch/amd64" instance.id=2db8d040-8f05-4b70-90c1-507f6b77a17d service=registry version=v2.1.0 
registry_1 | time="2015-08-12T14:35:13.875202246Z" level=info msg="response completed" http.request.host="localhost:5000" http.request.id=20854bc8-3998-453c-a0a1-19cf40eab5bb http.request.method=GET http.request.remoteaddr="172.17.42.1:36770" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-38-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.208746ms http.response.status=200 http.response.written=2 instance.id=2db8d040-8f05-4b70-90c1-507f6b77a17d service=registry version=v2.1.0 
registry_1 | 172.17.42.1 - - [12/Aug/2015:14:35:13 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-38-generic os/linux arch/amd64"
registry_1 | time="2015-08-12T14:35:22.146202208Z" level=debug msg="s3.List(\"/\")" instance.id=2db8d040-8f05-4b70-90c1-507f6b77a17d service=registry trace.duration=461.252498ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=294c4a8a-603b-486e-9d38-dbc712c443b1 trace.line=123 version=v2.1.0 
registry_1 | time="2015-08-12T14:35:32.024947938Z" level=debug msg="s3.List(\"/\")" instance.id=2db8d040-8f05-4b70-90c1-507f6b77a17d service=registry trace.duration=339.97475ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=7f844a00-9317-4a96-ad4c-2cb91bce9326 trace.line=123 version=v2.1.0
```

**Comment by dmp42** [comment]
Documentation is faulty.
You  need to use:

```

registry:
  environment:
    REGISTRY_STORAGE: "s3"
    REGISTRY_STORAGE_S3_ACCESSKEY: "XXXX"
    REGISTRY_STORAGE_S3_SECRETKEY: "XXXX"
    REGISTRY_STORAGE_S3_BUCKET: "my-docker-registry"
    REGISTRY_STORAGE_PATH: "/registry"
    REGISTRY_STORAGE_S3_REGION: "eu-west-1"
    REGISTRY_SEARCH_BACKEND: "sqlalchemy"
    REGISTRY_LOG_LEVEL: "debug"
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/docker.crt
    REGISTRY_HTTP_TLS_KEY: /certs/docker.key
    REGISTRY_AUTH: "htpasswd"
    REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
  volumes:
    - ssl:/certs
    - auth:/auth
  image: registry:2
  ports:
    - "5000:5000"
```

Note the extra **REGISTRY_AUTH: "htpasswd"** before the other keys.

Will fix the doc.
