### ISSUE TITLE
No support for s3 storage in new us-east-2 (Ohio)

### ISSUE THREAD

**Issue by eranchetz** [docker/docker-registry#1088]
Running the registry results in 
```
#config.yml 
....
storage:
    cache:
        layerinfo: inmemory
    s3:
        accesskey: ""
        secretkey: ""
        region: us-east-2
        bucket: example-docker-registry-ohio
```
Results in:
```
panic: Invalid region provided: us-east-2

```
