### ISSUE TITLE
EOF on push

### ISSUE THREAD

**Issue by donpinkster** [docker/docker-registry#121]
We are using hipache to forward all traffic to the docker-registry. When we are pushing an image the upload counter goes up to the desired size (713.3 MB) in this case.
When the size is reached we are getting the following error from Docker:

`2013/11/13 10:09:41 Failed to upload layer: Put http://registry.dev.company.net/v1/images/e63dd683c17b37ddfb30a54a974bcf13e33fbea5af8668d34e36db04ff4100ca/layer: EOF`

Hipache reports the following

```
13 Nov 09:09:41 - (worker #12) TCP timeout from {"remoteAddress":"172.17.42.1","remotePort":50762,"bytesWritten":0,"bytesRead":320630279,"elapsed":109.588}
13 Nov 09:09:41 - (worker #12) registry.dev.company.net: backend #0 reported an error ({"code":"ECONNRESET"}) while handling request for /v1/images/e63dd683c17b37ddfb30a54a974bcf13e33fbea5af8668d34e36db04ff4100ca/layer
13 Nov 09:09:41 - (worker #12) registry.dev.company.net: Response socket already closed, aborting.
```

The configuration we use for hipache is

```
{
    "server": {
        "debug": true,
        "accessLog": "/data/logs/hipache/access.log",
        "port": 80,
        "workers": 4,
        "maxSockets": 300,
        "deadBackendTTL": 0,
        "tcpTimeout": 1000,
        "retryOnError": 100,
        "deadBackendOn500": false,
        "httpKeepAlive": false,
        "lruCache": {
            "size": 5,
            "ttl": 5
        }
    }
}
```

The configuration for docker-registry is

```
# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    s3_access_key: REPLACEME
    s3_secret_key: REPLACEME
    s3_bucket: REPLACEME
    # Set a random string here
    secret_key: 6rdqUqBWsIqVRhBSqqkKUXvYm1tTd

prod:
    storage: local
    storage_path: /registry
    # Enabling this options makes the Registry send an email on each code Exception
    email_exceptions:
        smtp_host: REPLACEME
        smtp_login: REPLACEME
        smtp_password: REPLACEME
        from_addr: docker-registry@localdomain.local
        to_addr: info@company.com
```

Both the registry and hipache are running in docker itself.
We tried both the samalba/docker-registry image and from the project's Dockerfile.
