### ISSUE TITLE
docker pull through a mirroring registry fails with "gzip: invalid header"

### ISSUE THREAD

**Issue by cnelson** [docker/docker-registry#369]
Steps to reproduce:

Run the stock registry docker container with the following configuration:

```
mirroring:
    source: https://registry-1.docker.io
    source_index: https://index.docker.io
    tags_cache_ttl: 864000 # seconds
```

Perform a docker pull:

```
$ docker pull localhost:5000/ubuntu
Pulling repository localhost:5000/ubuntu
2014/05/20 00:08:00 Get http://localhost:5000/v1/repositories/ubuntu/images: gzip: invalid header
```

The issue seems to be that the mirroring code is returning the upstream's content-encoding header (in this case content-encoding: gzip) but the response body is not actually gzipped.

To verify this is the case;

```
$  curl --compressed --raw -v  http://localhost:5000/v1/repositories/ubuntu/images

Note: the < content-encoding: gzip header, but the body is in plain text.
```

Compared with hitting the upstream registry directly:

```
$ curl --compressed --raw -v https://index.docker.io/v1/repositories/ubuntu/images 

[body content is gzipped]
```

I assume something in the mirroring code is transparently unpacking the gzip and this is then being forwarded on to the client.
