### ISSUE TITLE
config can not work

### ISSUE THREAD

**Issue by ghost** [docker/docker-registry#439]
my /usr/local/lib/python2.7/dist-packages/config/config.yml:

```
dev:
    standalone: True
    storage: local
    storage_path: /opt/registry
    loglevel: debug

```

gunicorn command:

```
sudo gunicorn --access-logfile - --debug  -k gevent -b 0.0.0.0:80 -w 1 docker_registry.wsgi:application
```

when exec docker push image,the image always save in the current directory for the command gunicorn 
such as the current directory is /opt, the image save in /opt/tmp/images
by the way,docker-registry version is 0.8
configure file do not work? someone help me,3q.
