### ISSUE TITLE
Can't login to docker-registry 0.7.3 (POST /v1/users returns 404)

### ISSUE THREAD

**Issue by tommyblue** [docker/docker-registry#477]
After the update to version 0.7.3 (from 0.6.x) of docker-registry, I can't login anymore. `/v1/users` returns a 404 HTTP error (Not Found).

These are the logs from the registry container when I try to login:

```
[18/Jul/2014:12:45:46] "GET /v1/_ping HTTP/1.0" 200 4 "-" "Go 1.1 package http"
[18/Jul/2014:12:45:46] "POST /v1/users/ HTTP/1.0" 404 233 "-" "Go 1.1 package http"
```

The registry runs as a docker container and the host uses nginx with basic http auth, this is the configuration:

```
upstream docker-registry {
  server localhost:5000;
}
server {
  listen 443;
  server_name docker-registry.<MYDOMAIN>;

  ssl on;
  ssl_certificate /etc/ssl/certs/docker-registry.crt;
  ssl_certificate_key /etc/ssl/private/docker-registry.key;
  ssl_session_timeout 5m;

  ssl_protocols SSLv3 TLSv1;
  ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv3:+EXP;
  ssl_prefer_server_ciphers on;

  proxy_set_header Host             $http_host;   # required for docker client's sake
  proxy_set_header X-Real-IP        $remote_addr; # pass on real client's IP

  client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads

  # required to avoid HTTP 411: see Issue #1486 (https://github.com/dotcloud/docker/issues/1486)
  chunkin on;
  error_page 411 = @my_411_error;
  location @my_411_error {
    chunkin_resume;
  }

  location / {
    auth_basic              "Restricted";
    auth_basic_user_file    docker-registry.htpasswd;

    proxy_pass http://docker-registry;
  }

  location /_ping {
    auth_basic off;
    proxy_pass http://docker-registry;
  }

  location /v1/_ping {
    auth_basic off;
    proxy_pass http://docker-registry;
  }
}
```

This is `config.yml`:

```
common: &common
  loglevel: info
  search_backend: "_env:SEARCH_BACKEND:"
  sqlalchemy_index_database: "_env:SQLALCHEMY_INDEX_DATABASE:sqlite:////tmp/docker-registry.db"
  secret_key: <SECRET_KEY>

prod:
  loglevel: warn
  storage: local
  storage_path: /tmp/registry/
  smtp_host: localhost
  from_addr: <FROM_ADDR>
  to_addr: <TO_ADDR>
```

If I disable basic auth from the nginx conf, I obtain the same error `"GET /v1/_ping HTTP/1.0" 200` and `"POST /v1/users/ HTTP/1.0" 404`.

The error in the host trying to login is:

```
docker login docker-registry.drwolf.it:443
Username: <MY_USERNAME>
Password: 
Email: 
2014/07/18 14:53:33 Error response from daemon: (Code: 404; Headers: map[Server:[nginx/1.1.19] Date:[Fri, 18 Jul 2014 12:53:33 GMT] Content-Type:[text/html] Connection:[keep-alive] X-Docker-Registry-Version:[0.7.3] X-Docker-Registry-Config:[prod]])
```

The docker version is 1.1.1 build bd609d2
