### ISSUE TITLE
docker-registry  0.7.3 : Disk filling up 

### ISSUE THREAD

**Issue by sahilsk** [docker/docker-registry#954]
Hi,

In merely  2 days of operation docker registry(v0.7.3) is filling up disk space to 100%. And when we restart the resgitry disk space go back 0, clearing up all cached stuff.  Should not be its registry task to purge cache if disk reaching threshold value? Any help here would be great.

I'm  running registry inside docker with redis lru cache (it's also containerized) enabled.

``` sh
$ docker run  --restart=on-failure:10  -d -e SETTINGS_FLAVOR=prod  -e STORAGE_REDIRECT=true -v /opt/registry:/registry-conf  -e DOCKER_REGISTRY_CONFIG=/registry-conf/config.yml --link redis-cache:db --name registry-s3 -p 80:5000 registry:0.7.3
```
``` sh
root@prod-registry--10-91-0-13:/tmp# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                     NAMES
dfccc6c7dcsd       registry:0.7.3      "/bin/sh -c 'exec do   2 days ago          Up 2 days           10.x.x.x:80->5000/tcp   registry-s3
8b8389cecd4f       redis:latest        "/entrypoint.sh redi   2 days ago          Up 2 days           6379/tcp                  redis-cache
```

I am using s3 and my configuration looks like this:

``` yml
# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    # Bucket for storage
    boto_bucket: REPLACEME

     # Amazon S3 Storage Configuration
    s3_access_key: REPLACEME
    s3_secret_key: REPLACEME
    s3_bucket: REPLACEME
    s3_encrypt: false
    s3_secure: false

    # Set a random string here
    secret_key: REPLACEME


# This is the default configuration when no flavor is specified
dev:
    standalone: true
    storage: file
    storage_path: /tmp/registry
    loglevel: debug

# To specify another flavor, set the environment variable SETTINGS_FLAVOR
# $ export SETTINGS_FLAVOR=prod
prod:
    storage: s3
    storage_path: "/"
    # Enabling LRU cache for small files. This speeds up read/write on small files
    # when using a remote storage backend (like S3).
    standalone: True
    cache:
        host: _env:DB_PORT_6379_TCP_ADDR
        port: 6379
    cache_lru:
        host: _env:DB_PORT_6379_TCP_ADDR
        port: 6379

# This flavor is automatically used by unit tests
test:
    storage: local
    storage_path: /tmp/test
```
